baseURL = '/'
languageCode = 'en-us'
title = 'Squared Circle - Live Music'
theme = 'spectral'

[params]
fancyTitle = "<img src='/img/SC-Logo.png' width='30%' height='30%'/>" # title for frontpage, may include image
copyright = "Squared Circle"
description = '''
Classic-Rock aus dem Kreis Tuttlingen
'''
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["img/PPC_black.svg"]

[[params.menu.main]]
url = ''
title = "Home"

#[[params.menu.main]]
#url = '/home'
#title = "Events"

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
#phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
#email = "joernhauser@mailbox.org"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
#youtube = "@pinkpussycats5808"
#instagram = "bass_man_ppc"
dribble = ""

[params.one]
enable = false
body= '''
'''

[params.cta]
enable = true
title = "Downloads"
body = '''
Infos für Techniker und Presse.
'''

[[params.cta.link]]
href = "rider/Squared Circle - TechRider.pdf"
text = "Tech Rider"
special = false

[params.two]
enable = true

[[params.two.section]]
img = "img/2.jpg"
title = ""
body = '''
Squared Circle steht für ehrlichen, erdigen Rock 
seit über 20 Jahren mit eigenen Songs und Klassikern von Billy Idol bis ZZTop!

> If it's illegal to rock and roll, throw my ass in jail!  
-Kurt Cobain'''

#'''
#{{< youtube id="2P0XxF1_ozo" title="PPC Youtube Channel" >}}
#
#Folgt uns auf [Youtube](https://www.youtube.com/@pinkpussycats5808 "PPC") und [Instagram](https://www.instagram.com/bass_man_ppc/)!
#'''

[[params.two.section]]
img = "img/1.jpg"
title = 'Wir sind'
body = '''
(v.l.) Jan Flaig (Gitarre), Peter Sapski (Gesang), Patrick Borosch (Gesang), Steffen Scheffler (Bass/Keys), Jörn Hauser (Gitarre), Meik Morlock (Schlagzeug)
'''

[[params.two.section]]
#img = ""
title = 'Media'
body = '''

Hier eine Auswahl an Demos eigener Songs:
| Song |  |
|------------------|------------------------------------------------|
| Change your life | {{< audio src="music/Change your life.mp3" >}} |
| Wheel of fortune | {{< audio src="music/Wheel of fortune.mp3" >}} |

Videos von Gigs gibt es auf [Youtube](https://www.youtube.com/@SquaredCircleRocks "Squared Circle Rock")
'''

[[params.two.section]]
#img = ""
title = 'Kontakt'
body = '''
##### Booking
Meik Morlock (+49 176 66653672)  
##### Technische Fragen
Jörn Hauser (+49 176 82059964)
'''

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false